ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN whoami

USER snuser
ARG OLD_PYTHONPATH=${PYTHONPATH}
ENV PYTHONPATH=
ARG JIUWENSWARM_VERSION
RUN pip3.11 install -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --user jiuwenswarm==${JIUWENSWARM_VERSION}

RUN echo "revert python path: ${OLD_PYTHONPATH}"

USER sn
ENV PYTHONPATH=${OLD_PYTHONPATH}
