# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

"""Proactive engine — service that scans user conversations, updates the user
profile, and decides whether to proactively reach out with a skill recommendation,
task reminder, or need exploration message.

This is a pure service class that responds to external calls (from CronScheduler
or manual triggers). It does NOT run its own background tick loop.

Runs in AgentServer process. Decision is made by a proactive lightweight agent
(``set_proactive_agent``); the recommendation message is generated by the main
agent — tick triggers it via ``set_trigger_main_agent_callback``, so the message
naturally enters the main agent's context engine and streams to the frontend.

Usage:
- ``engine = ProactiveEngine(config)``
- ``engine.set_proactive_agent(proactive_agent)``
- ``engine.set_trigger_main_agent_callback(callback)``
- ``await engine.tick_now()`` — trigger a recommendation tick
"""

from __future__ import annotations

import logging
import re
import time

from typing import Any

logger = logging.getLogger(__name__)


# proactive 数值配置项的合法区间（与 web handler _validate_proactive_int 保持一致）。
_PROACTIVE_INT_LO = 1
_PROACTIVE_INT_HI = 50


def _safe_proactive_int(val: Any, default: int) -> int:
    """读取 proactive 数值配置项的防御性解析。

    config.yaml 被手改成非数字/浮点/超范围时，降级用 default + warning，不让引擎崩溃。
    （handler 写入时已校验，这里只防手改 config / 旧脏数据。）
    """
    # 先按字符串校验：挡住浮点(3.5)、科学计数(1e5)、字符串(abc)、空。
    # int(3.5) 在 Python 会静默截断成 3，不能直接 int()。
    raw = str(val).strip() if val is not None else ""
    if not re.fullmatch(r"[0-9]+", raw):
        logger.warning(
            "[ProactiveEngine] invalid int config %r, fallback to default %d", val, default,
        )
        return default
    n = int(raw)
    if n < _PROACTIVE_INT_LO or n > _PROACTIVE_INT_HI:
        logger.warning(
            "[ProactiveEngine] int config %r out of [%d,%d], fallback to default %d",
            val, _PROACTIVE_INT_LO, _PROACTIVE_INT_HI, default,
        )
        return default
    return n


class ProactiveEngine:
    """Proactive recommendation engine service.

    Each tick:
    1. Build a situation report from multi-session history + profile
    2. Single LLM call (via proactive agent): update profile + decide recommendation type
    3. If a decision is made: trigger main agent to generate message → streams to frontend
       (message naturally enters the main agent's context engine)

    This class does NOT run its own background loop. It is triggered by:
    - CronScheduler (via proactive.tick WebSocket request from Gateway),
      including the "run now" button in the Cron panel (also goes through
      proactive.tick — no separate manual-trigger endpoint).
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        config = config or {}
        self._max_per_day: int = _safe_proactive_int(config.get("max_recommend_per_day", 5), 5)
        self._max_rounds: int = _safe_proactive_int(config.get("max_rounds_per_tick", 20), 20)
        # 默认 False，与 config.yaml 的 proactive_recommendation.enabled 默认值一致，
        # 防御性默认=关闭，避免配置段缺失时引擎被误启用。
        self._enabled: bool = config.get("enabled", False)
        self._last_tick_at: float = 0.0
        # 推荐专用 agent：只做决策（无 session、无 tools、单轮、输出 JSON），
        # 替代 proactive_actions._analyze_and_decide 里的裸 model.invoke。
        self._proactive_agent: Any = None
        # 触发主 agent 跑一轮生成话术的回调。
        self._trigger_main_agent_callback: Any = None
        # 检查目标 channel 是否有活跃 agent（避免 agent 被 evict 后白调 LLM）。
        self._check_agent_available_callback: Any = None
        # 推送通知回调——直接推一条文本到前端，不经过主 agent（不进 context）。
        # 用于"今日推荐已达上限"等系统提醒。
        self._send_notification_callback: Any = None

    def set_proactive_agent(self, agent: Any) -> None:
        """Set the proactive lightweight agent used for recommendation decision.

        Args:
            agent: A DeepAgent instance (no tools, no task_loop, single-round).
                   Built by app_agentserver via create_deep_agent.
        """
        self._proactive_agent = agent

    @property
    def last_tick_at(self) -> float:
        """Last tick timestamp (public read accessor for ``_last_tick_at``)."""
        return self._last_tick_at

    def rebuild_proactive_agent(self, builder: Any) -> None:
        """Rebuild the proactive agent (e.g. after model config changed).

        The proactive agent is built once at AgentServer startup with the then-
        current model config. When the user changes models (frontend config
        save → agent.reload_config), the main agents hot-reload, but the
        proactive agent would keep the stale model. Call this to rebuild it
        with the latest model config.

        Args:
            builder: Callable ``() -> DeepAgent | None`` (the proactive_adapter
                     ``build_proactive_agent``), re-reads model config at call.
        """
        try:
            new_agent = builder()
            if new_agent is not None:
                self._proactive_agent = new_agent
                logger.info("[ProactiveEngine] proactive agent rebuilt (model config refreshed)")
        except Exception as exc:
            logger.warning("[ProactiveEngine] proactive agent rebuild failed: %s", exc)

    def set_trigger_main_agent_callback(self, callback: Any) -> None:
        """Set the callback that triggers the main agent to run one round."""
        self._trigger_main_agent_callback = callback

    def set_check_agent_available_callback(self, callback: Any) -> None:
        """Set the callback that checks if the target channel has an active agent."""
        self._check_agent_available_callback = callback

    def set_send_notification_callback(self, callback: Any) -> None:
        """Set the callback for pushing a simple text notification (no LLM, no context).

        用于"今日推荐已达上限"等系统提醒——直接推文本到前端，不触发主 agent。
        """
        self._send_notification_callback = callback

    def reload_config(self, config: dict[str, Any]) -> None:
        """Hot-reload configuration without restarting the process."""
        new_enabled = bool(config.get("enabled", False))
        new_max_per_day = _safe_proactive_int(config.get("max_recommend_per_day", self._max_per_day), self._max_per_day)
        new_max_rounds = _safe_proactive_int(config.get("max_rounds_per_tick", self._max_rounds), self._max_rounds)

        # 当日推荐计数 _daily_counts 不重置——它是"今天实际推了几条"的客观事实，清掉反而会让
        # 调小上限时 count 归零 < 新上限，在已超额的情况下继续推送，违反上限语义。
        # 上限提醒已改为前端弹窗 + 每次命中都推，无需清任何去重标记。

        self._max_per_day = new_max_per_day
        self._max_rounds = new_max_rounds
        self._enabled = new_enabled
        logger.info("[ProactiveEngine] config reloaded (enabled=%s, max_per_day=%d)",
                   new_enabled, new_max_per_day)

    async def tick_now(
        self,
        target_channel: str | None = None,
    ) -> bool:
        """Trigger a recommendation tick.

        This is the main API for external callers (CronScheduler, manual triggers).

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was made, False otherwise.
        """
        if not self._enabled:
            logger.debug("[ProactiveEngine] engine disabled, skipping tick")
            return False

        logger.info("[ProactiveEngine] tick_now called (target_channel=%s)", target_channel)
        try:
            pushed = await self._tick(target_channel=target_channel)
            return bool(pushed)
        except Exception as exc:
            logger.warning("[ProactiveEngine] tick_now failed: %s", exc, exc_info=True)
            return False

    async def _tick(self, target_channel: str | None = None) -> bool:
        """Single tick: build situation → analyze → push.

        Args:
            target_channel: Optional channel ID to deliver the recommendation to.
                          If None, uses the most recently active session.

        Returns:
            True if a recommendation was actually pushed to the channel,
            False if the tick was skipped for any reason (daily limit reached,
            empty situation, no model, no decision, cooldown, no delivery
            target). Callers (CronScheduler / manual trigger) should use this
            to report an accurate status instead of assuming "sent".
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _today_recommend_count,
            _increment_daily_count,
            _is_cooled_down,
            _mark_recommended,
            _get_all_skills,
            _analyze_and_decide,
            _trigger_main_agent,
        )
        from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
            load_recommendation_state,
            save_recommendation_state,
        )
        from jiuwenswarm.agents.harness.common.recommendation.situation_report import (
            build_situation_report,
        )

        # 每次 tick 顺手清理过期数据（daily_counts 老日期 key、cooldown_records 过期项）。
        try:
            self.run_maintenance()
        except Exception as exc:
            logger.debug("[ProactiveEngine] maintenance failed: %s", exc)

        # Step 0: 检查目标 channel 是否有活跃 agent——agent 被 evict 后白调 LLM 是浪费 token。
        if self._check_agent_available_callback is not None:
            try:
                if not self._check_agent_available_callback(target_channel):
                    logger.debug("[ProactiveEngine] no active agent for channel=%s, skipping tick", target_channel)
                    self._last_tick_at = time.time()
                    return False
            except Exception as exc:
                logger.debug("[ProactiveEngine] check_agent_available failed: %s", exc)

        # Gate: daily budget
        if _today_recommend_count() >= self._max_per_day:
            logger.info("[ProactiveEngine] daily limit reached (%d/%d), skipping tick",
                       _today_recommend_count(), self._max_per_day)
            # 推送通知提醒用户已到上限。前端拦截 source=proactive_notification 后改走
            # 顶部弹窗（不进会话历史），故这里每次命中上限都推一次，无需去重。
            if self._send_notification_callback is not None:
                try:
                    await self._send_notification_callback(
                        target_channel,
                        f"今日主动推荐已达每日上限（{self._max_per_day} 条），"
                        f"明日恢复。",
                    )
                except Exception as exc:
                    logger.debug("[ProactiveEngine] send_notification failed: %s", exc)
            self._last_tick_at = time.time()
            return False

        # ── Step 1: Build situation report ─────────────────────
        _, available_skills = _get_all_skills()
        report = await build_situation_report(
            max_rounds=self._max_rounds,
            skills=available_skills,
        )

        if report.is_empty():
            logger.debug("[ProactiveEngine] situation report empty, skipping tick")
            self._last_tick_at = time.time()
            return False

        report_text = report.render_for_llm()

        # ── Step 2: LLM analysis + decision ────────────────────
        state = load_recommendation_state()
        if self._proactive_agent is None:
            logger.debug("[ProactiveEngine] no proactive agent available, skipping tick")
            self._last_tick_at = time.time()
            return False

        result = await _analyze_and_decide(
            report_text, state, available_skills, self._proactive_agent,
        )

        # ── Step 3: Check if we have a recommendation ───────────
        decision = result.decision
        if not decision:
            logger.debug("[ProactiveEngine] no recommendation this tick")
            self._last_tick_at = time.time()
            return False

        # ── Step 4: Cooldown check ─────────────────────────────
        if not _is_cooled_down(decision.target, state):
            logger.debug("[ProactiveEngine] '%s' still in cooldown, skipping", decision.target)
            self._last_tick_at = time.time()
            return False

        # ── Step 5: Pick delivery target ───────────────────────
        # 两种触发（cron 自然到点 / Cron 面板"立即执行"）统一：都用"最活跃会话"。
        # find_session_for_channel / most_recent_active_session 的选法已修：不再要求历史
        # 完整、_scan_sessions 走缓存拿最新 last_message_at，故刚发消息、assistant 还没
        # 回完的当前会话也能被准确选为最活跃会话。
        if target_channel:
            target_session = report.find_session_for_channel(target_channel)
            if not target_session:
                logger.debug("[ProactiveEngine] no session found for channel '%s'", target_channel)
                self._last_tick_at = time.time()
                return False
        else:
            target_session = report.most_recent_active_session()
            if not target_session:
                logger.debug("[ProactiveEngine] no active session for delivery")
                self._last_tick_at = time.time()
                return False

        # ── Step 6: Trigger main agent to generate & deliver ────
        # fire-and-forget：trigger_main_agent 把主 agent 跑一轮丢后台 task，立即返回
        # True（表示"已触发"），让调用方 cron 秒回不超时。Step 7 的状态更新不在
        # 这里立即做，而是包成 on_delivered 回调——后台 task 真正跑完、推荐确实送达
        # 后才回调执行计数/持久化，避免"触发即计数、后台失败却已计数"的名不副实。
        if self._trigger_main_agent_callback is None:
            logger.warning("[ProactiveEngine] no trigger_main_agent_callback, skipping")
            self._last_tick_at = time.time()
            return False

        def _on_delivered() -> None:
            """后台送达后才执行的状态更新（Step 7）。"""
            _increment_daily_count()
            _mark_recommended(decision.target, state)
            state.add_recommendation({
                "type": decision.type,
                "target": decision.target,
                "reason": decision.reason,
                "urgency": decision.urgency,
                "tick_at": time.time(),
                "session_id": target_session.session_id,
            })
            state.touch()
            save_recommendation_state(state)
            logger.info("[ProactiveEngine] delivered '%s' (type=%s, urgency=%.2f, session=%s)",
                         decision.target, decision.type, decision.urgency,
                         target_session.session_id[:20])

        triggered = await _trigger_main_agent(
            session_id=target_session.session_id,
            channel_id=target_channel,
            decision=decision,
            trigger_callback=self._trigger_main_agent_callback,
            on_delivered=_on_delivered,
        )
        if not triggered:
            logger.info("[ProactiveEngine] not triggered (session busy, duplicate inflight, "
                        "or trigger failed), skipping")
            self._last_tick_at = time.time()
            return False

        # 已 fire-and-forget 触发：立即返回，后台跑完会回调 _on_delivered 做计数。
        # cron 端不等主 agent，秒回不超时；_last_tick_at 立即更新让下次 tick 排程正常。
        self._last_tick_at = time.time()
        return True

    # ── Maintenance helpers (called by Cron or manually) ─────────

    @staticmethod
    def run_maintenance() -> None:
        """Prune stale data from daily counts and cooldown records.

        This should be called periodically (e.g., by Cron) to keep the
        recommendation state clean.
        """
        from jiuwenswarm.agents.harness.common.recommendation.proactive_actions import (
            _prune_daily_counts,
            _prune_cooldown_records,
        )
        from jiuwenswarm.agents.harness.common.recommendation.profile_extractor import (
            load_recommendation_state,
            save_recommendation_state,
        )

        _prune_daily_counts()
        state = load_recommendation_state()
        _prune_cooldown_records(state)
        save_recommendation_state(state)
        logger.debug("[ProactiveEngine] maintenance completed")
