# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.

""" /rewind summarize 的 partial compact prompt 模板 """

NO_TOOLS_PREAMBLE = (
    "CRITICAL: Respond with TEXT ONLY. Do NOT call any tools.\n\n"
    "- Do NOT use any tools whatsoever.\n"
    "- You already have all the context you need in the conversation above.\n"
    "- Tool calls will be REJECTED and will waste your only turn.\n"
    "- Your entire response must be plain text: an <analysis> block followed by a <summary> block.\n\n"
)

# 'from': model sees messages after the pivot (tail). Summary will follow retained prefix.
PARTIAL_COMPACT_PROMPT = (
    "Your task is to create a detailed summary of the RECENT portion "
    "of the conversation \u2014 the messages that follow earlier "
    "retained context. The earlier messages are being kept intact and "
    "do NOT need to be summarized. Focus your summary on what was "
    "discussed, learned, and accomplished in the recent messages only.\n"
    "\n"
    "Before providing your final summary, wrap your analysis in "
    "<analysis> tags to organize your thoughts. In your analysis "
    "process:\n"
    "1. Chronologically analyze each message and section. Thoroughly "
    "identify:\n"
    "   - The user's explicit requests and intents\n"
    "   - Your approach to addressing the user's requests\n"
    "   - Key decisions, technical concepts and code patterns\n"
    "   - Specific details like file names, code snippets, function "
    "signatures, file edits\n"
    "   - Errors that you ran into and how you fixed them\n"
    "   - Specific user feedback, especially if the user told you to "
    "do something differently\n"
    "2. Double-check for technical accuracy and completeness.\n"
    "\n"
    "Your summary should include the following sections:\n"
    "\n"
    "1. Primary Request and Intent: Capture the user's explicit "
    "requests and intents from the recent messages\n"
    "2. Key Technical Concepts: List important technical concepts, "
    "technologies, and frameworks discussed recently.\n"
    "3. Files and Code Sections: Enumerate specific files and code "
    "sections examined, modified, or created. Include full code "
    "snippets where applicable and include a summary of why this file "
    "read or edit is important.\n"
    "4. Errors and fixes: List errors encountered and how they were "
    "fixed.\n"
    "5. Problem Solving: Document problems solved and any ongoing "
    "troubleshooting efforts.\n"
    "6. All user messages: List ALL user messages from the recent "
    "portion that are not tool results.\n"
    "7. Pending Tasks: Outline any pending tasks from the recent "
    "messages.\n"
    "8. Current Work: Describe precisely what was being worked on "
    "immediately before this summary request.\n"
    "9. Optional Next Step: List the next step related to the most "
    "recent work. Include direct quotes from the most recent "
    "conversation.\n"
    "\n"
    "Here's an example of how your output should be structured:\n"
    "\n"
    "<example>\n"
    "<analysis>\n"
    "[Your thought process, ensuring all points are covered thoroughly "
    "and accurately]\n"
    "</analysis>\n"
    "\n"
    "<summary>\n"
    "1. Primary Request and Intent:\n"
    "   [Detailed description]\n"
    "\n"
    "2. Key Technical Concepts:\n"
    "   - [Concept 1]\n"
    "   - [Concept 2]\n"
    "\n"
    "3. Files and Code Sections:\n"
    "   - [File Name 1]\n"
    "      - [Summary of why this file is important]\n"
    "      - [Important Code Snippet]\n"
    "\n"
    "4. Errors and fixes:\n"
    "    - [Error description]:\n"
    "      - [How you fixed it]\n"
    "\n"
    "5. Problem Solving:\n"
    "   [Description]\n"
    "\n"
    "6. All user messages:\n"
    "    - [Detailed non tool use user message]\n"
    "\n"
    "7. Pending Tasks:\n"
    "   - [Task 1]\n"
    "\n"
    "8. Current Work:\n"
    "   [Precise description of current work]\n"
    "\n"
    "9. Optional Next Step:\n"
    "   [Optional Next step to take]\n"
    "\n"
    "</summary>\n"
    "</example>\n"
    "\n"
    "Please provide your summary based on the RECENT messages only "
    "(after the retained earlier context), following this structure "
    "and ensuring precision and thoroughness in your response.\n"
)

# 'up_to': model sees messages before the pivot (prefix). Summary will precede kept recent messages.
PARTIAL_COMPACT_UP_TO_PROMPT = (
    "Your task is to create a detailed summary of this conversation. "
    "This summary will be placed at the start of a continuing session; "
    "newer messages that build on this context will follow after your "
    "summary (you do not see them here). Summarize thoroughly so that "
    "someone reading only your summary and then the newer messages can "
    "fully understand what happened and continue the work.\n"
    "\n"
    "Before providing your final summary, wrap your analysis in "
    "<analysis> tags to organize your thoughts. In your analysis "
    "process:\n"
    "1. Chronologically analyze each message and section. Thoroughly "
    "identify:\n"
    "   - The user's explicit requests and intents\n"
    "   - Your approach to addressing the user's requests\n"
    "   - Key decisions, technical concepts and code patterns\n"
    "   - Specific details like file names, code snippets, function "
    "signatures, file edits\n"
    "   - Errors that you ran into and how you fixed them\n"
    "   - Specific user feedback, especially if the user told you to "
    "do something differently\n"
    "2. Double-check for technical accuracy and completeness.\n"
    "\n"
    "Your summary should include the following sections:\n"
    "\n"
    "1. Primary Request and Intent: Capture the user's explicit "
    "requests and intents in detail\n"
    "2. Key Technical Concepts: List important technical concepts, "
    "technologies, and frameworks discussed.\n"
    "3. Files and Code Sections: Enumerate specific files and code "
    "sections examined, modified, or created. Include full code "
    "snippets where applicable and include a summary of why this file "
    "read or edit is important.\n"
    "4. Errors and fixes: List errors encountered and how they were "
    "fixed.\n"
    "5. Problem Solving: Document problems solved and any ongoing "
    "troubleshooting efforts.\n"
    "6. All user messages: List ALL user messages that are not tool "
    "results.\n"
    "7. Pending Tasks: Outline any pending tasks.\n"
    "8. Work Completed: Describe what was accomplished by the end of "
    "this portion.\n"
    "9. Context for Continuing Work: Summarize any context, decisions, "
    "or state that would be needed to understand and continue the work "
    "in subsequent messages.\n"
    "\n"
    "Here's an example of how your output should be structured:\n"
    "\n"
    "<example>\n"
    "<analysis>\n"
    "[Your thought process, ensuring all points are covered thoroughly "
    "and accurately]\n"
    "</analysis>\n"
    "\n"
    "<summary>\n"
    "1. Primary Request and Intent:\n"
    "   [Detailed description]\n"
    "\n"
    "2. Key Technical Concepts:\n"
    "   - [Concept 1]\n"
    "   - [Concept 2]\n"
    "\n"
    "3. Files and Code Sections:\n"
    "   - [File Name 1]\n"
    "      - [Summary of why this file is important]\n"
    "      - [Important Code Snippet]\n"
    "\n"
    "4. Errors and fixes:\n"
    "    - [Error description]:\n"
    "      - [How you fixed it]\n"
    "\n"
    "5. Problem Solving:\n"
    "   [Description]\n"
    "\n"
    "6. All user messages:\n"
    "    - [Detailed non tool use user message]\n"
    "\n"
    "7. Pending Tasks:\n"
    "   - [Task 1]\n"
    "\n"
    "8. Work Completed:\n"
    "   [What was accomplished]\n"
    "\n"
    "9. Context for Continuing Work:\n"
    "   [Context needed to continue]\n"
    "\n"
    "</summary>\n"
    "</example>\n"
    "\n"
    "Please provide your summary based on the conversation, following "
    "this structure and ensuring precision and thoroughness in your "
    "response.\n"
)
